### PR TITLE
Add canonical links to blog.skohub.io

### LINKED ISSUE #78: Set canonical links to SkoHub blog for all SkoHub posts
With the SkoHub blog being set up, we need to add a `<link rel="canonical">` link in the HTML `<head>`, see https://github.com/skohub-io/skohub-blog/issues/1#issuecomment-871990377.

I am not sure how to best do this with Jekyll. Maybe we can do it by adjusting this:

https://github.com/hbz/lobid-blog/blob/74864ef9b7ac6ad213b493724b7f37ffed4746bc/_layouts/default.html#L9

(The idea came to me when seeing https://gist.github.com/bennylope/1894706#gistcomment-2821633 but  am not familiar with Jekyll.)

### PR DESCRIPTION
**Pull request by acka47**
Resolves #78

### CODE REVIEW

**Comment by acka47** [comment]
Oups, doesn't work locally as expected.

**Comment by acka47** [comment]
Now it should work. Please review, @fsteeg .

**Comment by fsteeg** [comment]
Hm, I'm still getting lobid URLs as canonical links, e.g. `<link rel="canonical" href="http://blog.lobid.org/2020/10/09/skohub-apconf.html" />` for `http://127.0.0.1:4000/2020/10/09/skohub-apconf.html`

**Comment by fsteeg** [comment]
Did `bundle install`, tried `jekyll clean`, then `jekyll serve --drafts --watch`.

**Comment by acka47** [comment]
Hm, strange. It definitely works on my system with the `78-setCanonicalLinks` branch. I also jsut tried is after a fresh `git clone` and it worked (although I had some other problems there with ruby). Maybe the browser caching? You can also run `jekyll build` and then look e.g. at `lobid-blog/_site/2019/09/27/presenting-skohub-vocabs.html`.

**Review by fsteeg — APPROVED** [review]
Right, good you mentioned the branch. I had so much trouble getting the `bundle install` / `ruby` stuff to work, I forgot to switch the branch. Now it works here. However, the blog.skohub.io links give me SSL warnings, and non-https redirects to https. If that's expected, you could merge (deployment happen automatically after merge here, right?)

**Comment by acka47** [comment]
> However, the blog.skohub.io links give me SSL warnings, and non-https redirects to https.

We received the SSL certificate on Tuesday but apparently it hasn't been installed yet. Will merge nonetheless.

**Pull request merged**
