### PR TITLE
Create 2023-08-21-giving-lobid-organisations-some-love-and-updates.md

### PR DESCRIPTION
**Pull request by TobiasNx**
Könnt ihr mal auf den Blogpost schauen? Es ist für die Umstellung für lobid organisations.

### CODE REVIEW

**Review by dr0i — CHANGES_REQUESTED** [review]
Besides one grammar thing and the removing of relative time references +1

**Review by dr0i — COMMENTED** [review]
deploying with jekyll: title is missing

**Review by acka47 — APPROVED** [review]
I made not unsignificant changes and additions. Please review yourself again, @TobiasNx . +1 from me

**Review by dr0i — APPROVED** [review]
The quotation marks were the problems re title. Now it's fine.

**Pull request merged**
